services:
  mysql:
    container_name: mysql
    image: mysql
    networks:
      - camunda-network
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/conf:/etc/mysql/conf.d
      - /home/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform
    networks:
      - camunda-network
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - DB_URL=jdbc:mysql://mysql:3306/camunda
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - WAIT_FOR=mysql:3306
networks:
  camunda-network:
    driver: bridge